### ISSUE TITLE
remove Chrome font cache

### ISSUE THREAD

**Issue by sgsax** [lemtek/Powershell#1]
ChromeDWriteFontCache in the user Chrome profile can also get pretty big and is recreated as needed when the browser is restarted. Add the following to the Chrome section:

`Remove-Item -path "C:\Users\$($_.Name)\AppData\Local\Google\Chrome\User Data\Default\ChromeDWriteFontCache" -Recurse -Force -EA SilentlyContinue -Verbose`

I don't know git well enough to do a pull request, otherwise I would have just done that.

**Comment by lemtek** [comment]
Thanks for the suggestion.  I'll put this in as an option.
